### ISSUE TITLE
out of date repo?

### ISSUE THREAD

**Issue by declann** [peasy-ui/peasy-ui#2]
Hey!

Really like the peasy-ui solution to managing state!

I came across it on GameDevShift discord and this tutorial: https://gamedevshift.com/posts/pong-hathora-peasy#peasy-ui-front-end
which links to this repo.

I believe development now happens here:

https://github.com/peasy-lib/peasy-lib/blob/main/packages/peasy-ui/README.md

It might be useful to link that in this repo and/or archive this one?
Also, discord link in readme no longer works.

Great work, and I look forward to checking the peasy game engine stuff in peasy-lib.

Cheers!
Declan

**Comment by jwx** [comment]
Hi Declan!

Glad to hear you like `peasy-ui`! You're absolutely right in that it now is a part of `peasy-lib` and has moved to the repo you mentioned. I've updated the readme in this repo to point to the new one. Thanks for letting me know and hope to hear from you again regarding `peasy-ui` and the other `peasy-lib` libraries.

Cheers!
Jürgen
